name: check update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */5 * *'
jobs:
  check-update:
    name: check update
    runs-on: windows-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          cache: 'pip'
      - run: pip install -r scripts/requirements.txt

      - name: check and generate new version
        run: python scripts/mainUpdate.py

      - name: update!
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/update.js')
            await script({github, context})
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update
