name: keygen

on:
  issues:
    types: opened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v6
      env:
        KEYGEN_JS_CODE: ${{ secrets.KEYGEN_JS_CODE }}
      with:
        script: |
          const script = require('./keygen.js')
          await script({github, context, core})
